### ISSUE TITLE
When binding a shortcut to `/` , it only triggers for the dedicated `/` on the numpad

### ISSUE THREAD

**Issue by hognevevle** [fabiospampinato/shortcuts#1]
Thank you for a great library!

I noticed that when I bind a shortcut to `/`, it will not trigger when I press Shift+7, which is where the forward slash exists in my (Norwegian) keyboard layout. If I press the dedicated `/` key on the numpad (code `NumpadDevide`), it works as expected.

As I'm pretty sure `Shift+7` isn't consistent for all keyboard layouts, is there any way to bind this shortcut in such a way that it works across the board for the different combinations that produce a `/`?

**Comment by hognevevle** [comment]
By the way, here is an example of the keyboard event in question (shift+7) which doesn't trigger the shortcut defined for `/`.

![CleanShot 2021-04-07 at 21 20 07](https://user-images.githubusercontent.com/2721188/113922005-0f9b2f00-97e7-11eb-86b8-64820743bf44.png)

**Comment by fabiospampinato** [comment]
I should look into this, it feels like unless you have another shortcut bound to Shift+7 the library should already detect that a "/" was written in a keypress event and handle the relevant shortcut properly. As that doesn't seem to be happening I think this is a bug.

**Comment by fabiospampinato** [comment]
@hognevevle could you check if this got fixed in v3?

**Comment by fabiospampinato** [comment]
Closing for lack of more info.
