### ISSUE TITLE
how to trigger keyUp event?

### ISSUE THREAD

**Issue by Thomas365** [fabiospampinato/shortcuts#5]
I use it but I cant trigger keyup event, I need use event type to handle different situation.

**Comment by fabiospampinato** [comment]
@Thomas365 I'm not sure what you mean, this library doesn't trigger events, it lists to them. The current event is passed to shortcut handler, it looks like you could already use that to do different things depending on the event type, for example `return false` to let the event bubble up and let some other shortcut handle it potentially.

Let me know if that doesn't address your problem already.
