### ISSUE TITLE
Support disabling sequences when recording

### ISSUE THREAD

**Issue by seiyria** [fabiospampinato/shortcuts#7]
for some reason, when I do shortcuts.record(), very rarely do I only get the singular key I pressed to do the record - I get a sequence of all keys pressed before that one, as well (`1 1 1 1 2` instead of `2`). I can obviously trim this by removing all but the last result when doing record, but it feels really hacky. How do I make it so record only ever gives me 1 key? Or maybe I can turn off sequence handling to achieve this?

**Comment by fabiospampinato** [comment]
The record feature is pretty low level, it just gives you all the keys that have been pressed more or less. Perhaps that should be refined somewhat.

**Comment by fabiospampinato** [comment]
Recording support got offloaded to [shosho](https://github.com/fabiospampinato/shosho). I don't see disabling recording sequences, you can just split the sequence by a space and take the last section if you want to.
